services:
  web:
    build: ./backend
    container_name: dev-django
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: always
    networks:
        - app-network

  db:
    image: postgres:16
    container_name: dev-db
    volumes:
      - database_volume:/var/lib/postgresql/data/
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network
      
volumes:
  database_volume:

networks:
  app-network:
    driver: bridge